//! `INSERT` / `UPDATE` / `DELETE` skeletons for the schema tree's **Generate**
//! menu — the statement a person is about to write, with its shape already
//! correct.
//!
//! **These are drafts for a human, not statements for a server**, and every
//! decision below follows from that. Values are named placeholders (`:price`),
//! which no engine accepts — so a skeleton that reaches the editor and is run by
//! reflex *fails to parse* rather than writing a row of empty strings or
//! updating every row in the table. Filling one in is the user's next act, and
//! until they do, nothing can happen by accident.
//!
//! What each statement addresses is not invented here: the table name is
//! [`crate::filter::qualified_table_name`] (so a generated `UPDATE` and the
//! browse `SELECT` above it spell the table identically) and the `WHERE` is
//! [`crate::schema::browse_key_columns`], the same key the grid's write-back
//! addresses a row with. A table with no key at all gets a `WHERE` that says so
//! and does not parse, because the alternative — omitting it — is a statement
//! that runs against every row.
//!
//! The `CREATE` half of that menu is not here: it is `DbSchema`'s own
//! `create_ddl_script`, which emits real DDL rather than a draft.

use crate::filter::qualified_table_name;
use crate::intel::SqlDialect;
use crate::schema::{ColumnInfo, TableInfo, browse_key_columns};

/// The placeholder standing in for a column's value: `:name`.
///
/// Named rather than `?` so a wide `INSERT` still says which slot is which once
/// the column list has scrolled off, and deliberately *not* a literal of any
/// kind — see the module note on why a skeleton must not be runnable.
fn placeholder(column: &str) -> String {
    format!(":{column}")
}

/// Is this column worth typing a value for in a generated statement?
///
/// Stricter than [`ColumnInfo::is_server_assigned`], and the two must not be
/// confused. That one answers "the server **rejects** an explicit value" and is
/// the rule every real write path obeys. This one also drops `AUTO_INCREMENT` /
/// `serial` / `GENERATED BY DEFAULT AS IDENTITY` keys, which *do* accept a value
/// — nobody hand-writing an `INSERT` wants to supply one, and import, which
/// genuinely does, keeps asking the other predicate.
fn worth_writing(c: &ColumnInfo) -> bool {
    !c.is_server_assigned() && !c.auto_increment
}

/// The columns a skeleton names, longest-standing rule first: everything worth
/// writing, or — when that leaves nothing, as it does for a table that is one
/// `AUTO_INCREMENT` key — every column, since a statement naming no columns at
/// all is not a draft of anything.
fn skeleton_columns(t: &TableInfo) -> Vec<&ColumnInfo> {
    let worth: Vec<&ColumnInfo> = t.columns.iter().filter(|c| worth_writing(c)).collect();
    if worth.is_empty() {
        t.columns.iter().collect()
    } else {
        worth
    }
}

/// The `WHERE` line addressing one row, or the comment that says why there
/// isn't one.
///
/// The no-key form is deliberately **not** valid SQL. A skeleton with no `WHERE`
/// is an `UPDATE`/`DELETE` over the whole table one keystroke away from running;
/// a `WHERE` the parser rejects is a question the user has to answer first, and
/// the reason is written where they are already looking.
fn where_clause(t: &TableInfo, dialect: SqlDialect) -> String {
    let key = browse_key_columns(t);
    if key.is_empty() {
        return format!(
            "WHERE /* no primary key or unique index on {} — add a condition */",
            t.name
        );
    }
    let conds: Vec<String> = key
        .iter()
        .map(|c| {
            format!(
                "{} = {}",
                crate::export::ident_if_needed(c, dialect),
                placeholder(c)
            )
        })
        .collect();
    format!("WHERE {}", conds.join(" AND "))
}

/// `INSERT INTO t (cols) VALUES (:cols);`
pub fn insert_skeleton(dialect: SqlDialect, database: &str, t: &TableInfo) -> String {
    let name = qualified_table_name(dialect, database, t.schema.as_deref(), &t.name);
    let cols = skeleton_columns(t);
    let names: Vec<String> = cols
        .iter()
        .map(|c| crate::export::ident_if_needed(&c.name, dialect))
        .collect();
    let values: Vec<String> = cols.iter().map(|c| placeholder(&c.name)).collect();
    format!(
        "INSERT INTO {name} ({})\nVALUES ({});",
        names.join(", "),
        values.join(", ")
    )
}

/// `UPDATE t SET col = :col, … WHERE key = :key;`
///
/// The key columns are *not* in the `SET` list — rewriting the value a row is
/// addressed by is not what an update usually means — unless they are all the
/// table has, which is a junction table, where they are exactly what one means.
pub fn update_skeleton(dialect: SqlDialect, database: &str, t: &TableInfo) -> String {
    let name = qualified_table_name(dialect, database, t.schema.as_deref(), &t.name);
    let key = browse_key_columns(t);
    let cols = skeleton_columns(t);
    let settable: Vec<&&ColumnInfo> = cols.iter().filter(|c| !key.contains(&c.name)).collect();
    let sets: Vec<String> = if settable.is_empty() {
        cols.iter().collect()
    } else {
        settable
    }
    .iter()
    .map(|c| {
        format!(
            "{} = {}",
            crate::export::ident_if_needed(&c.name, dialect),
            placeholder(&c.name)
        )
    })
    .collect();
    format!(
        "UPDATE {name}\nSET {}\n{};",
        sets.join(",\n    "),
        where_clause(t, dialect)
    )
}

/// `DELETE FROM t WHERE key = :key;`
pub fn delete_skeleton(dialect: SqlDialect, database: &str, t: &TableInfo) -> String {
    let name = qualified_table_name(dialect, database, t.schema.as_deref(), &t.name);
    format!("DELETE FROM {name}\n{};", where_clause(t, dialect))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::TableInfo;

    /// `actor`, as MySQL reports it: an `AUTO_INCREMENT` key and three columns
    /// worth typing.
    fn actor() -> TableInfo {
        let mut t = TableInfo {
            name: "actor".to_string(),
            ..Default::default()
        };
        t.columns = vec![
            col("actor_id", true, true),
            col("first_name", false, false),
            col("last_name", false, false),
            col("last_update", false, false),
        ];
        t
    }

    fn col(name: &str, primary_key: bool, auto_increment: bool) -> ColumnInfo {
        ColumnInfo {
            name: name.to_string(),
            type_name: "varchar(45)".to_string(),
            nullable: false,
            primary_key,
            auto_increment,
            ..Default::default()
        }
    }

    #[test]
    fn an_insert_names_every_column_the_server_will_not_fill() {
        assert_eq!(
            insert_skeleton(SqlDialect::MySql, "sakila", &actor()),
            "INSERT INTO sakila.actor (first_name, last_name, last_update)\n\
             VALUES (:first_name, :last_name, :last_update);"
        );
    }

    #[test]
    fn a_generated_column_is_never_named() {
        // The server rejects an explicit value for one, so naming it would make
        // the draft wrong rather than merely verbose.
        let mut t = actor();
        t.columns.push(ColumnInfo {
            name: "full_name".to_string(),
            generated: Some("concat(first_name,' ',last_name)".to_string()),
            ..col("full_name", false, false)
        });
        assert!(!insert_skeleton(SqlDialect::MySql, "sakila", &t).contains("full_name"));
    }

    #[test]
    fn a_table_that_is_only_a_server_assigned_key_still_produces_a_draft() {
        // Nothing is "worth writing", and `INSERT INTO t () VALUES ()` is not a
        // draft of anything — so the key comes back rather than an empty list.
        let mut t = actor();
        t.columns.truncate(1);
        assert_eq!(
            insert_skeleton(SqlDialect::MySql, "sakila", &t),
            "INSERT INTO sakila.actor (actor_id)\nVALUES (:actor_id);"
        );
    }

    #[test]
    fn an_update_sets_the_columns_and_addresses_the_row_by_its_key() {
        assert_eq!(
            update_skeleton(SqlDialect::MySql, "sakila", &actor()),
            "UPDATE sakila.actor\n\
             SET first_name = :first_name,\n    \
                 last_name = :last_name,\n    \
                 last_update = :last_update\n\
             WHERE actor_id = :actor_id;"
        );
    }

    #[test]
    fn a_delete_is_the_same_where_and_nothing_else() {
        assert_eq!(
            delete_skeleton(SqlDialect::MySql, "sakila", &actor()),
            "DELETE FROM sakila.actor\nWHERE actor_id = :actor_id;"
        );
    }

    #[test]
    fn a_composite_key_is_addressed_in_full() {
        let mut t = actor();
        t.columns = vec![
            col("film_id", true, false),
            col("actor_id", true, false),
            col("note", false, false),
        ];
        assert!(
            delete_skeleton(SqlDialect::MySql, "sakila", &t)
                .ends_with("WHERE film_id = :film_id AND actor_id = :actor_id;"),
            "{}",
            delete_skeleton(SqlDialect::MySql, "sakila", &t)
        );
    }

    #[test]
    fn a_junction_table_of_nothing_but_key_columns_still_sets_something() {
        // Every column is part of the key, so the usual "don't rewrite what you
        // address the row by" rule would leave `SET` empty — which is not a
        // statement. Here rewriting them is exactly what an update means.
        let mut t = actor();
        t.columns = vec![col("film_id", true, false), col("actor_id", true, false)];
        let sql = update_skeleton(SqlDialect::MySql, "sakila", &t);
        assert!(
            sql.contains("SET film_id = :film_id,\n    actor_id = :actor_id"),
            "{sql}"
        );
    }

    #[test]
    fn a_table_with_no_key_gets_a_where_that_cannot_run() {
        // The whole point: no `WHERE` at all would be an UPDATE over every row,
        // one reflex keystroke away.
        let mut t = actor();
        t.columns = vec![col("body", false, false)];
        let sql = update_skeleton(SqlDialect::MySql, "notes", &t);
        assert!(
            sql.contains("WHERE /* no primary key or unique index on actor — add a condition */"),
            "{sql}"
        );
        assert!(!sql.contains("WHERE body"), "{sql}");
    }

    #[test]
    fn a_value_is_never_a_literal() {
        // A skeleton that runs is a skeleton that can write junk by reflex.
        let sql = insert_skeleton(SqlDialect::MySql, "sakila", &actor());
        assert!(!sql.contains("''"), "{sql}");
        assert!(!sql.contains("NULL"), "{sql}");
        assert!(sql.contains(":first_name"), "{sql}");
    }

    #[test]
    fn each_engine_addresses_the_table_the_way_it_can_reach_it() {
        let mut t = actor();
        t.schema = Some("sales".to_string());
        // Postgres: the connection is already inside the database, so the
        // namespace is the qualifier (and `public` needs none).
        assert!(
            delete_skeleton(SqlDialect::Postgres, "shop", &t)
                .starts_with("DELETE FROM sales.actor")
        );
        t.schema = Some("public".to_string());
        assert!(delete_skeleton(SqlDialect::Postgres, "shop", &t).starts_with("DELETE FROM actor"));
        // SQLite: one file, nothing to qualify with.
        t.schema = None;
        assert!(delete_skeleton(SqlDialect::Sqlite, "main", &t).starts_with("DELETE FROM actor"));
    }

    #[test]
    fn a_name_that_needs_quoting_gets_it() {
        let mut t = actor();
        t.name = "order".to_string();
        t.columns = vec![col("id", true, false), col("select", false, false)];
        let sql = insert_skeleton(SqlDialect::MySql, "my db", &t);
        assert!(
            sql.starts_with("INSERT INTO `my db`.`order` (id, `select`)"),
            "{sql}"
        );
    }

    #[test]
    fn a_key_the_server_does_not_fill_is_named_like_any_other_column() {
        // The rule is "the server will fill this in", not "this is the key" — a
        // plain (non-`AUTO_INCREMENT`) primary key has to be supplied by whoever
        // writes the row, so leaving it out would make the draft wrong.
        let mut t = actor();
        t.columns = vec![col("code", true, false), col("label", false, false)];
        assert_eq!(
            insert_skeleton(SqlDialect::MySql, "sakila", &t),
            "INSERT INTO sakila.actor (code, label)\nVALUES (:code, :label);"
        );
    }
}
